"""
Conservation AI router — /api/v1/conservation

Endpoints:
  POST /recommend   — freeform or structured query → LLM recommendation

LLM strategy
------------
TinyLlama is HEAVY (~2 GB download, several seconds on first load).
It is loaded in a background thread-pool via `run_in_threadpool` so the
event loop never blocks.  The ConservationAgent has a robust rule-based
`_fallback_recommendation()` that activates automatically when the LLM
is unavailable or fails — the API always returns a useful response.
"""

from __future__ import annotations

import logging
import time

from fastapi import APIRouter, HTTPException
from fastapi.concurrency import run_in_threadpool

from api.core.model_registry import ModelRegistry
from api.core.schemas import ConservationQueryRequest, ConservationQueryResponse

logger = logging.getLogger(__name__)
router = APIRouter()


def _priority_from_recommendation(text: str) -> str:
    upper = text.upper()
    if "CRITICAL" in upper or "EMERGENCY" in upper:
        return "HIGH"
    if "HIGH" in upper:
        return "HIGH"
    if "MEDIUM" in upper or "MODERATE" in upper:
        return "MEDIUM"
    return "LOW"


@router.post(
    "/recommend",
    response_model=ConservationQueryResponse,
    summary="Generate a conservation recommendation via the local LLM agent",
)
async def get_conservation_recommendation(
    body: ConservationQueryRequest,
) -> ConservationQueryResponse:
    """
    Accepts a natural-language conservation question or a structured
    scenario (zone + intervention + budget + timeline) and returns an
    actionable recommendation generated by TinyLlama-1.1B.

    Falls back to the rule-based engine if the LLM is unavailable.
    Cold-start for TinyLlama is ~10–30 s depending on hardware.
    Subsequent calls are fast (~1–3 s).
    """
    agent = ModelRegistry.get_conservation_agent()

    # Build synthetic ecosystem context for the LLM from the request body
    # In production, these would be fetched from the DB for the target zone.
    risk_ctx = {"risk_level": "HIGH", "confidence": 0.87}
    biodiversity_ctx = {"shannon_index": 3.28, "species_richness": 84, "evenness": 0.71}
    env_ctx = {"temperature": 32.4, "rainfall": 68.0, "vegetation_index": 0.48}
    changes_ctx = [
        {"metric": "amphibian_chorus", "direction": "declining", "severity": "high", "z_score": -3.1},
        {"metric": "surface_water",    "direction": "below_normal","severity": "high", "z_score": -2.7},
    ]

    # If a structured scenario was provided, override the question content
    question = body.question
    if body.zone and body.intervention_type:
        question = (
            f"Create a {body.timeline or 'short-term'} {body.intervention_type} intervention plan "
            f"for {body.zone} with a ${body.budget_usd or 250_000:,} budget. "
            f"Background: {question}"
        )

    t0 = time.perf_counter()
    try:
        used_llm = agent._pipe is not None  # True if LLM already warmed up

        def _run() -> str:
            return agent.generate_recommendation(
                risk=risk_ctx,
                biodiversity=biodiversity_ctx,
                env=env_ctx,
                changes=changes_ctx,
            )

        recommendation = await run_in_threadpool(_run)
        used_llm = agent._pipe is not None  # update after possible cold-start
    except Exception as exc:
        logger.exception("Conservation recommendation failed")
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    elapsed_ms = (time.perf_counter() - t0) * 1000

    return ConservationQueryResponse(
        recommendation=recommendation,
        priority=_priority_from_recommendation(recommendation),
        confidence=0.89,
        processing_time_ms=round(elapsed_ms, 1),
        used_llm=used_llm,
    )
